# 在该文件所在目录下运行 docker compose up -d
#-----------------------------------------

version: '3'

services:
  mongodb:
    container_name: easy-mock-mongodb
    image: mongo:3.4.1
    volumes:
      # 数据库文件存放地址，根据需要修改为本地地址
      - '/home/easy-mock/data/db:/data/db'
    networks:
      - easy-mock
    restart: always

  redis:
    container_name: easy-mock-redis
    image: redis:4.0.6
    command: redis-server --appendonly yes
    volumes:
      # redis数据文件存放地址，根据需要修改为本地地址
      - '/home/easy-mock/data/redis:/data'
    networks:
      - easy-mock
    restart: always

  web:
    container_name: easy-mock
    image: easymock:fix
    command: /bin/bash -c "npm start"
    ports:
      - 7300:7300
    volumes:
      # 日志地址，根据需要修改为本地地址
      - '/home/easy-mock/logs:/home/easy-mock/easy-mock/logs'
      # 配置地址，没有则将使用config文件夹下的default.json
      # - '/home/easy-mock/production.json:/home/easy-mock/easy-mock/config/production.json'
    networks:
      - easy-mock
    restart: always

networks:
  easy-mock:
